spring.application.name=backend

server.port=${SERVER_PORT:8080}
frontend_base_url=${front_base_url}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/interviewMate_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.forward-headers-strategy=native
management.endpoint.health.cache.time-to-live=0ms

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=2000ms
spring.data.redis.ssl.enabled=true

# prod 프로필이 켜질 때 oauth 프로필도 세트로 같이 켜지도록 그룹화
spring.profiles.group.prod=prod,oauth

logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.orm.jdbc.bind=info
logging.level.org.springframework.security=info

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=50MB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


logging.level.root=INFO
logging.level.com.project.backend=DEBUG